### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/memegen#1]
@MB-Finski Awesome!

Here is a first bunch of remarks and hints:

* You can set the width and height of .meme-caps-dialog to 100% in GetCapsDialog otherwise it overflows when the container is too small. I couldn't see the caption inputs on my laptop's screen with 20% zoom level :-)
* It's better to pass data to child components via props instead of having a refs on them and call their methods.
The selected meme could be passed as a prop to the GetCapsDialog component.
GetCapsDialog could be rendered only if a meme is selected.
The selected meme data variable would get cleared when GetCapsDialog would be closed (it would emit a 'close' event that MemeCustomPickerElement would listen to)
* You can remove the 'has-previous' and 'has-next' properties of the NcModal in GetCapsDialog (or set them to false but it's their default value). These are useful to navigate when you show a list of pictures for example.
* Line 75 of MemeReferenceWidget.vue, wrong class name, should be meme-wrapper
* In MemeReferenceWidget, you could use a v-if on the `<strong>` tag to render it only if richObject.alt is defined
* We usually don't include the compiled javascript code in our repos (there are some exceptions like the server repo). You can even add the js/ directory to .gitignore. In general, we never include what can be generated, the sources are enough.
* Line 9 of PickerResult.vue, the title is still saying it's a GIF :-)
* As your app is compatible with NC >= 27, you can use Php 8 features like short class attributes declaration in the constructor like https://github.com/nextcloud/integration_openai/blob/main/lib/Service/OpenAiAPIService.php#L43-L48 . Just adding private/protected/public in front of a constructor param makes it a class attribute. We can talk about Php8 stuff next week.
* We usually try to break long lines. For example when making a function call with a lot of parameters, one can break on each parameter. Also, line breaks for each array member is way easier to read.
* What do you think about removing the search provider now that the smart picker provider is the main way to use the app?

**Comment by MB-Finski** [comment]
Thanks for the detailed hints! I think I have these solved in the latest master. Also, fixed some css errors that I noticed while at it.

Regarding the search provider... You're probably right. It could be removed.
